import SwiftUI

// `Color.warmBackground`, `Color.cardBackground`, and `Color.warmInk` are
// generated by Xcode from the corresponding colorsets in Assets.xcassets.
extension View {
    /// Replaces the default grouped scroll background with the app's warm canvas.
    /// Apply to any `List`, `Form`, or `ScrollView` shown full-screen.
    func warmBackground() -> some View {
        self
            .scrollContentBackground(.hidden)
            .background(Color.warmBackground.ignoresSafeArea())
    }

    /// Styled navigation bar title: bold, rounded, warm brown ink.
    /// Overrides the visible title; keep `.navigationTitle` alongside it so
    /// back buttons and accessibility still get the plain string.
    func warmNavigationTitle(_ title: String) -> some View {
        self.toolbar {
            ToolbarItem(placement: .principal) {
                Text(title)
                    .font(.title3.weight(.bold))
                    .fontDesign(.rounded)
                    .foregroundStyle(Color.warmInk)
            }
        }
    }
}
